### ISSUE TITLE
Update Navbar

### ISSUE THREAD

**Issue by kiran-ghorpade** [rutikbkale/portfolio#1]
![image](https://github.com/rutikbkale/portfolio/assets/115089102/56fac6ed-8dd8-403e-b533-db595b139ccb)

If you don't mind,
I think there is a spelling mistake "Contract Me". 

If you have time to correct it, Please Update your portfolio.
Your Porfolio website is Amazing. It gives proper information about your skills and projects.

Sorry for adding this issue.
I'm just exploring how github Issues works, btw.

**Comment by rutikbkale** [comment]
Thanks for your correction. I will modify my portfolio. Once again thank you.
